export const actionType = {
    AUTH_REGISTER: "AUTH_REGISTER",
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_INFO: "AUTH_INFO",
    REGISTRANT_GET: "REGISTRANT_GET",
    REGISTRANT_STORE: "REGISTRANT_STORE",
    REGISTRANT_SHOW: "REGISTRANT_SHOW",
    REGISTRANT_UPDATE: "REGISTRANT_UPDATE",
    REGISTRANT_DELETE: "REGISTRANT_DELETE",
}